### ISSUE TITLE
Latest 0.0.0.3 upload to Hackage fails to build on Windows

### ISSUE THREAD

**Issue by sumo** [sjakobi/bsb-http-chunked#22]
The tar.gz file has files dated "Jan  1  1970" which may be the reason. Everything works okay with cabal on FreeBSD but Windows 10 generates an error.

``
cabal.exe: Failed to unpack bsb-http-chunked-0.0.0.3 (which is required by
exe:transparent-server from transparent-bots-0.1.0.0). The exception was:
D:\msys64\home\sumo\dev\transparent-bots\dist-newstyle\tmp\src-10136\bsb-http-chunked-0.0.0.3\:
setModificationTime:setFileTimes: invalid argument (The parameter is
incorrect.)
`` 

Cabal is:
``
cabal-install version 2.4.0.0
compiled using version 2.4.0.1 of the Cabal library
``
GHC is:
``
The Glorious Glasgow Haskell Compilation System, version 8.4.3
``

**Comment by sjakobi** [comment]
Thanks for the report! This appears to be [an issue with cabal new-sdist](https://github.com/haskell/cabal/issues/5596).

I uploaded v0.0.0.4 using the old `cabal dist`.

**Comment by sjakobi** [comment]
I've also deprecated v0.0.0.3 on Hackage.
